### ISSUE TITLE
Issues with postgres

### ISSUE THREAD

**Issue by joelbitar** [divio/djangocms-text-ckeditor#13]
I get an error when I'm deploying my project to my production server where I use prostgresql.

relation "cmsplugin_text" does not exist
LINE 1: ...."cmsplugin_ptr_id", "cmsplugin_text"."body" FROM "cmsplugin...

Is there some obious solution to this and what can I do to help?

**Comment by ShivangPandey** [comment]
Yeah I resolved this issue....the main thing was that i was using django 1.7 and by default it was trying to run south migrations so in order to resolve that i just added this to MIGRATION_MODULE under the settings.py:
'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',

This will explicitly tell the framework to run migrations instead of south migrations.
Since the main issue was djangocms_text_ckeditor's table was not getting created under the db
