### ISSUE TITLE
CMS Plugins dropdown appears empty 

### ISSUE THREAD

**Issue by 8ksoft** [divio/djangocms-text-ckeditor#214]
Hi,

I'm using  Django==1.6.8, djangocms==3.0.7 and djangocms-text-ckeditor==2.4.3. When open the CK Editor, I see CMS Plugin dropdown as always, but when click on them, the options list appears empty, as show in the picture below.

![captura](https://cloud.githubusercontent.com/assets/989490/5672715/f0c90146-9771-11e4-90f1-9c3345200649.jpg)

In settings I have included the following configuration.
```
CMS_PLACEHOLDER_CONF = {
    'articulo_contenido_1': {
        'plugins': ['TextPlugin', 'PicturePlugin'],
        'text_only_plugins': ['LinkPlugin'],
        'extra_context': {"width":640},
        'name': gettext("Content"),
        'language_fallback': True,
        'default_plugins': [
            {
                'plugin_type': 'TextPlugin',
                'values': {
                    'body':'<p>Lorem ipsum dolor sit amet...</p>',
                },
            },
        ],
        'child_classes': {
            'TextPlugin': ['PicturePlugin', 'LinkPlugin'],
        },
        'parent_classes': {
            'LinkPlugin': ['TextPlugin'],
        },
    },
}
```
When I comment the CMS_PLACEHOLDER_CONF, all plugins appears in the dropdown normally. I think there is no typo error in this setting. Do you see anything wrong?

**Comment by 8ksoft** [comment]
Downgrade to version 2.3.0 makes that the plugin dropdown works again.

**Comment by yakky** [comment]
Can't reproduce on the standard django CMS project or a custom project by copy/pasting the above placeholder configuration

@mkoistinen @evildmp @ojii could you give this a try?

**Comment by darbula** [comment]
Same thing here, downgrading to 2.3.0 brought back the plugin dropdown.

**Comment by darbula** [comment]
@yakky to reproduce this user has to be staff and not superuser.

**Comment by darbula** [comment]
Also after downgrading to 2.3.0. all plugins are shown - `CMS_PLACEHOLDER_CONF` plugins is not respected.

**Comment by yakky** [comment]
@darbula could you test latest master with django CMS 3.0.12? I still can't reproduce using a staff user with all permission (CMS_PERMISSION on and off) and the above ``CMS_PLACEHOLDER_CONF``

**Comment by darbula** [comment]
Everything is fine, the mistake was in my `CMS_PLACEHOLDER_CONF` I did not realize that `"plugin"` is the primary plugin filter for placeholder i.e. that every plugin has to be listed there or in `"text_only_plugins"`, that is, I thought that listing plugins in `"child_classes"` was enough to let them be selected in `TextPlugin`. Additionally `"text_only_plugins"` was not used (it seems deprecated because `"parent_classes"` can be used to restrict plugins as a child of `TextPlugin`) and all this was enough to make confusion. Reading again documentation it all seems clear and precise but my initial understanding was different and then I saw this issue and taught this must be it. On the other hand, @8ksoft configuration seems fine, he did not have same configuration mistakes thus the issue should probably left open.

**Comment by yakky** [comment]
@darbula thanks for your feedback
@8ksoft could you retest this on latest master / django CMS 3.0.12?

**Comment by 8ksoft** [comment]
Sorry for my late feedback. I can confirm that the problem persist with django-cms 3.0.14 and djangocms-text-ckeditor==2.4.3. Maybe some problem with my environment (I have a lot of apps installed, including djangocms-ckeditor-filer). I will try this with a clean environment and share my feedback.

**Comment by cstrap** [comment]
Downgrading djangocms-text-ckeditor from 2.4.3 to 2.3.0 all plugins are shown.
My environment:
```
django==1.6.11
django-cms>3.0,<3.1
djangocms-text-ckeditor==2.3.0
```

**Comment by snejy** [comment]
I still experience this issue with django-cms==3.1.4 I tried djangocms-text-ckeditor with versions 2.3.0, 2.5.2, 2.7.0 but changing version does not solve the problem.
