### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by faidoc** [divio/djangocms-text-ckeditor#323]
Hi

Is it possible to align an image whitin a text?

I can't do it. Just pasted a text and inserting an image with left alignment to be on the left of the text (in the editor looks good), but when publishing, I see the image on top of the text. I don't see any style printed within the img tag like float:left.

Thanks

**Comment by FinalAngel** [comment]
@faidoc it should either add ``style="text-align:left;`` or something like ``class="left"`` is either of that available? If not screenshots or a screencast would help to understand the problem.

**Comment by faidoc** [comment]
Hi
Yeah sure, here are some pics showing how it looks on the editor, with indeed the float:left, and how it look when publishing the page.

I also noticed in the documentation something about sanitized data... maybe the style attribute is being erased when viewing the front? I tried with the following settings but with the same result (also, I don't know if I can use the parameter 'image2_alignClasses' from CKEDITOR (tried with it and without it), is it there where I have to put it? Or it isn't supported at all?:

```
# CKEditor
CKEDITOR_SETTINGS = {
    'language': 'es',
    'skin': 'bootstrapck',
    'basicEntities': False,
    'entities': False,
    'image2_alignClasses': [ 'align-left', 'align-center', 'align-right' ],
}
TEXT_HTML_SANITIZE = False
TEXT_ADDITIONAL_ATTRIBUTES = ('style')
```

![1](https://cloud.githubusercontent.com/assets/331390/15842381/3c3f4314-2c1e-11e6-8347-5ab23b698829.jpg)
![2](https://cloud.githubusercontent.com/assets/331390/15842382/3c47da6a-2c1e-11e6-8f17-60ab7724db16.jpg)
![3](https://cloud.githubusercontent.com/assets/331390/15842383/3c60528e-2c1e-11e6-9740-cc98cafc0c1d.jpg)

**Comment by vxsx** [comment]
Hi @faidoc 

at the moment it is not possible to align images in the text plugin using ckeditor's "align" feature on the toolbar. Since images inserted inserted in the ckeditor are actually cms plugins, the cannot be affected from ckeditor itself (at least at the moment).

Depending on the image plugin you use, they should have different settings, e.g. for aldryn-bootstrap3 one in advanced settings there's a classes field that can be used to align image to the left (also i've removed img-responsive):

![screen shot 2016-06-07 at 08 47 45](https://cloud.githubusercontent.com/assets/366813/15848318/9473ee90-2c8c-11e6-9171-990da48d726b.png)

Or in case of filer image plugin:
![screen shot 2016-06-07 at 08 47 45](https://cloud.githubusercontent.com/assets/366813/15848349/c6ee401e-2c8c-11e6-926d-247bbdd97499.png)

Which adds `filer_image left` classes, which can be styled to properly align the image.

**Comment by FinalAngel** [comment]
Thanks for clarifying @vxsx
