### ISSUE TITLE
Including newly installed plugin for ckeditor

### ISSUE THREAD

**Issue by jschon1991** [divio/djangocms-text-ckeditor#334]
I tried to install btgrid to ckeditor (with success), it shows up and worked.
Then I tried install same plugin to djangocms_text_ckeditor... 
I added plugin to static/djangocms_text_ckeditor/ckeditor/plugins/
I have configured layout in settings.py (added btgrid to layout), and in config.js I have config.extraPlugins = 'btgrid'; and all its dependencies. (btgrid button didn't show up in toolbar)
When I use config from builded ckeditor it shows up in djangocms_text_ckeditor but some features from djangocms_text_ckeditor disapears (like cmsplugins and so..), even when I add cmsplugins to config.plugins = '...';

**Comment by vxsx** [comment]
Currently overriding extraPlugins is a little bit problematic because it is a string.
You can use https://github.com/divio/djangocms-text-ckeditor#ckeditor_settings this method of overriding view settings, and providing your own extraPlugins, but you will have to manually add these https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/js/cms.ckeditor.js#L48

We will make it easier to extend without having to specify djangocms-text-ckeditor specific plugins explicitly.

**Comment by vxsx** [comment]
Should be fixed since 3.3

You can now just add your plugins via `config.extraPlugins = 'btgrid';`
