### ISSUE TITLE
CMS_PLACEHOLDER_CONF 'limits' appears to have gotten broken between 3.3.3 and 3.4.1

### ISSUE THREAD

**Issue by mikemcgowan** [divio/djangocms-text-ckeditor#398]
Please [see here](https://github.com/divio/django-cms/issues/5754) for a description of the problem which I originally incorrectly raised in Django-CMS itself, but infact appears to be a problem specific to this plugin (as neither `LinkPlugin` nor `FilePlugin` manifest the problem).

**Comment by gatsinski** [comment]
I have the same issue. When I try to add a new TextPlugin the [has_reached_plugin_limit](https://github.com/divio/django-cms/blob/3.4.5/cms/utils/plugins.py#L233) function is called twice. The first time it passes successfully because there is no plugin attached to the placeholder. Before the second call however an empty CMSPlugin is created and it is the one that causes the problem because this time the limit check is about to fail. Both times the function is called in [admin/forms.py](https://github.com/divio/django-cms/blob/3.4.5/cms/admin/forms.py#L799).

I am using:
Django==1.8.18
django-cms==3.4.5
Djangocms-text-ckeditor==3.5.3
