### ISSUE TITLE
Multiple HTMLFields can't have different configurations

### ISSUE THREAD

**Issue by gmenih341** [divio/djangocms-text-ckeditor#418]
I'm trying to have two different `HTMLFIeld`'s, both using different configurations. Example model:

```python
class SomeModel(CMSPlugin):
    title = HTMLField(configuration='CKEDITOR_HEADING_CONF')
    text = HTMLField(configuration='CKEDITOR_SUBTITLE_CONF', blank=True)
```

Both `title` and `text` will use the `CKEDITOR_HEADING_CONF`.

**Comment by sidneijp** [comment]
Looks like the problem is in the logic used on the template:

djangocms_text_ckeditor/templates/cms/plugins/widgets/ckeditor.html

Already in the first rendering of the ckeditor it loops through all ".CMS_CKEditor:visible" on the page and initializes them with the configuration of this first ckeditor. Additionally the lines:

`
                if (editor.data('isCKEditorInitialized')) {
                    return;
                }
                editor.hide();
                editor.data('isCKEditorInitialized', true);
`

ensure that the next rendering will not setup the CKeditor again.

**Comment by sidneijp** [comment]
I've sent a pull request fixing it. It basically change the selector used in the init function from `.CMS_CKEditor:visible` to `{{ ckeditor_selector }}:visible`
