### ISSUE TITLE
Adding cms plugin in ckeditor strips existing inline style tag

### ISSUE THREAD

**Issue by db654** [divio/djangocms-text-ckeditor#428]
I'm currently experiencing this in version 3.1 after an upgrade from 2.8.1 where it worked correctly, tho testing newer versions did not appear to resolve the issue. 

Given this piece of markup:
`<span style="font-size:20px;">Text</span>`

If I highlight this text in ckeditor, then attach a filer link plugin and save, the existing span tag and its inline style is lost -- resulting in this:
`<cms-plugin alt="Link - Text " id="6182" render-plugin="true" title="Link - Text"><a href="#">Text</a></cms-plugin>`

Though I wasn't overring AllowedContent, I did try adding  `'extraAllowedContent': 'cms-plugin[*]'` as a fix to no avail.

**Comment by vxsx** [comment]
Can it be that when you select the text and replace it with a plugin it actually replaces the span?
Can you switch to "Source" mode and then wrap the cms plugin with the span you need and then switch back out of source and back into it to see if it's still in place (switching triggers ckeditor's filters). If the span is still in there after those switches, then it probably is an issue with ckeditor itself as it was upgraded since 2.8.1.

**Comment by furiousdave** [comment]
Yeah, if you add the span or em or whatever back in after creating the cms plugin, it doesn't get stripped again. It's only on the initial creation of the cms plugin that all inline tags within that highlighted text get removed.

All started, I think, after the switch to the <cms-plugin> tags, which are otherwise great, but if you think it's more likely a ckeditor bug, I'll dig into that as well.

**Comment by vxsx** [comment]
Yeah. It's probably a change in the way they treat selections across those versions.

The way we insert the plugin is we take the current selection in ckeditor and replace it with the preview of the plugin wrapped in those special tags, then make a ckeditor widget out of it. The important part here is the selection contents replacement.
 
So yeah, I think what happens is in 2.8.1 it wasn't greedy for outer inline tags, now it is.

**Comment by furiousdave** [comment]
Thanks a lot for the info. If I come across some kind of configuration change or workaround, I'll post back here for future reference.
